### ISSUE TITLE
More pic

### ISSUE THREAD

**Issue by remynln** [Mai-Sakurajima-Group/mai-sakurajima#1]
I think we could add a picture of all her emotions (angry, happy, sad, etc...)

**Comment by ghost** [comment]
On it pog

**Comment by remynln** [comment]
If you need help I can do it

**Comment by ghost** [comment]
Be my guest ;)

**Comment by remynln** [comment]
Do you prefer folders with emotions like upset/README.md and upset photos of mai or everything in the main readme ?

**Comment by ghost** [comment]
folders with all the emotions sounds good!
